#!/bin/bash

ERROR_FLAG=0
MAX_AMOUNT_OF_APP=100000
AMOUNT_APPS_TO_INSTALL=$MAX_AMOUNT_OF_APP

usage() { echo "Usage: apkInstaller [man|-a|-n <amount> |-s <serialNumber> |-d <directory>]"; exit 1; }

simpleMan() { #todo: add "man" page
	echo "man page"
	exit 0;
}

# trigger simple man page
if [ "$1" = "man" ]; then
	simpleMan
fi

# args: apps amount | directory | serial number
install() {
	echo "Installing... on device $3"
	
	x=1
	for i in $( find $2 -name "*.apk" ); do
       		adb -s $3 install -dg $i
       		if [ $x -ge "$1" ]; then
          		break;
       		fi
		((x++))
    	done

	echo "Installed $x apps on device $3";
}

# args: apps amout | directory
install_On_All_Devices() {
	for SERIAL_NBR in $(adb devices | tail -n +2 | cut -sf 1); do
		install $1 $2 $SERIAL_NBR
	done
}

while getopts ":an:s:d:" OPTION; do
	case $OPTION in
	  a)
		a="notempty"
		;;
	  d)
		d=${OPTARG}
		;;
	  n)
		n=${OPTARG}
		;;
	  s)
		s=${OPTARG}
		;;
	  \?)
		usage
		;;
	  :)
		usage
		;;
	esac
done

#parse options and args -> validate user input

if [ ! -z "${a}" ] && [ ! -z "${s}" ]; then
	echo "ERROR: Install to all (-a) or by serial number (-s)." 
	ERROR_FLAG=1
fi

if [[ ! -z "${d}" ]] && [[ ! -d "${d}" ]]; then
	echo "ERROR: Provide directory as arg of -d option."
	ERROR_FLAG=1
elif [[ -z "${d}" ]]; then
	d='.' 
fi

if [ ! -z "${n}" ] && [[ ${n} -le 0 ]]; then
	echo "ERROR: Install more than 0 apps"
	ERROR_FLAG=1
elif [ ! -z "${n}" ]; then 
	AMOUNT_APPS_TO_INSTALL=$n
fi

if [[ $ERROR_FLAG -eq 1 ]]; then
	exit 1
fi

# main part

if [ ! -z "${s}" ]; then
	install $AMOUNT_APPS_TO_INSTALL ${d} ${s}
else
	install_On_All_Devices $AMOUNT_APPS_TO_INSTALL ${d}
fi

#all work is done!
exit 0
